### ISSUE TITLE
"tsd-s3cmd --register" errors: No such file or directory: '/home/<user>/.config/tacl'

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-s3cmd#2]
Running ``tsd-s3cmd --register`` gives a non-intuitive error:
```
(base) ofrei@comorment:~$ tsd-s3cmd --register
Traceback (most recent call last):
  File "/nrec/projects/ofrei/miniconda3/bin/tacl_admin", line 14, in <module>
    from tsdapiclient.configurer import read_config, update_config, print_config, \
  File "/nrec/projects/ofrei/miniconda3/lib/python3.9/site-packages/tsdapiclient/configurer.py", line 11, in <module>
    TACL_CONFIG = get_config_path() + '/config'
  File "/nrec/projects/ofrei/miniconda3/lib/python3.9/site-packages/tsdapiclient/tools.py", line 113, in get_config_path
    config_path.mkdir()
  File "/nrec/projects/ofrei/miniconda3/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ofrei/.config/tacl'
```
Workaround is to simply create those folders - but it's non-intuitive, thanks to @Sandeek for pointing this out!
```
(base) ofrei@comorment:~$ mkdir /home/ofrei/.config
(base) ofrei@comorment:~$ mkdir /home/ofrei/.config/tacl
```

**Comment by leondutoit** [comment]
Fixed in https://github.com/unioslo/tsd-api-client/commit/7cb066f386515a6f06fed440f2019c074dd7983b will publish a new release to PyPi.

**Comment by leondutoit** [comment]
Now fixed with https://github.com/unioslo/tsd-s3cmd/commit/018e734dfb38ef015ce6e5c3c339036ca10821cb
